# Generated by Django 3.2.8 on 2021-12-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(max_length=1000, verbose_name='About Me')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=1000, verbose_name='Hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='myportfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=150, verbose_name='Surname')),
                ('picture', models.ImageField(upload_to='images/')),
                ('github', models.CharField(max_length=250, verbose_name='Git link')),
                ('bitbucket', models.CharField(max_length=250, verbose_name='BitBucket Link')),
                ('linkedin', models.CharField(max_length=250, verbose_name='Linkedin')),
                ('fb', models.CharField(max_length=250, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=250, verbose_name='Instagram Link')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('git_link', models.CharField(blank=True, max_length=255, null=True)),
                ('public_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=100, verbose_name='Resume Name')),
                ('qr_code_pic', models.ImageField(upload_to='cv/', verbose_name='Image Field')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_school', models.CharField(max_length=1000, verbose_name='Study')),
                ('high_school', models.CharField(max_length=1000, verbose_name='High School Name')),
                ('bachelor_degree', models.CharField(max_length=1000, verbose_name='University Name and Department')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=1000, verbose_name='Work Experiences')),
                ('position', models.TextField(max_length=100, verbose_name='Position at that job')),
                ('start_date', models.DateTimeField(verbose_name='Job Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Job End Date')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
